### ISSUE TITLE
Add an Endpoint to get Agent Info

### ISSUE THREAD

**Issue by ntindle** [e2b-dev/agent-protocol#39]
**Is your feature request related to a problem? Please describe.**
I've run into a case where I need to display different agent details as needed based on the agent. 

Things such as: 
- Name
- Version

**Describe the solution you'd like**
I would like a `GET` Endpoint Added to the protocol to request information about the agent

**Describe alternatives you've considered**
Requiring this information to be queriable outside the agent protocol is possible, but non linear

**Comment by ntindle** [comment]
Another thing we discussed was

Author,
Help Text

**Comment by ntindle** [comment]
`Continue Message`: `yes` or `continue` or something like that

**Comment by jzanecook** [comment]
I believe we've settled on the following format for a route existing at `/ap/v1/agent/info`:

```json
{
    "name": "My Agent",
    "description": "General purpose agent.",
    "version": "1.0.0",
    "protocol": "1.0",
    "github": "https://github.com/myagent/myagent",
    "url": "https://myagent.com",
    "docs": "https://myagent.com/docs",
    "issues": "https://github.com/myagent/myagent/issues"
}
```

**Comment by jzanecook** [comment]
Additionally to this schema we discussed having a `config_options` array of objects with the properties of type, default, description,and options (optional). Where type refers to the type of input, and options is an array of that type that show what is available. This `config_options` array would be used as an info endpoint for clients to use against the tasks and steps in their config options.

**Comment by hackgoofer** [comment]
We should also have the "schema_plugin" array that is the plugin system

**Comment by jzanecook** [comment]
Here is the AgentInfo object I had been thinking of using for the spec:

```yml

    AgentInfo:
      type: object
      properties:
        name:
          description: Name of the agent.
          type: string
          example: My Agent
        description:
          description: Description of the agent.
          type: string
          example: My agent is the best agent.
        version:
          description: Version of the agent.
          type: string
          example: 1.0.0
        protocol_version:
          description: Version of the agent protocol.
          type: string
          example: 1
        github:
          description: GitHub repository of the agent.
          type: string
          example: 'https://github.com/AI-Engineers-Foundation/agent-protocol'
        url:
          description: URL of the agent.
          type: string
          example: 'https://my-agent.com'
        docs:
          description: Link to the documentation of the agent.
          type: string
          example: 'https://my-agent.com/docs'
        issues:
          description: Link to the issues of the agent.
          type: string
          example: 'https://github.com/AI-Engineers-Foundation/agent-protocol/issues'
        config_options:
          description: List of configuration options for the agent's tasks and steps. The config is a user-defined set of key/value pairs where the values are standard but the keys are not.
          type: object
          example: |-
            {
            "debug": {
            "type": "boolean",
            "default": false,
            "description": "Whether to run the agent in debug mode."
            },
            "model": {
            "type": "string",
            "default": "gpt-4",
            "description": "The model in which the agent's tasks should run."
            }
            }
          additionalProperties:
            type: object
            properties:
              type:
                description: The type of the value.
                type: string
                enum:
                  - string
                  - integer
                  - float
                  - boolean
                  - list
                  - dict
              default:
                description: The default value of the config option.
                type: string
              description:
                description: 'A description of the value with type, default value, and description.'
                type: string
              options:
                description: A list of options for the config option.
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: integer
                    - type: number
                    - type: boolean
                    - type: object
                    - type: array
                      items:
                        oneOf:
                          - type: string
                          - type: integer
                          - type: number
                          - type: boolean
                          - type: object
            required:
              - type
              - default
              - description
            example: |-
              {
              "type": "string",
              "default": "gpt-4",
              "description": "Model for the agent's steps to use."
              "options": ["gpt-4", "gpt-3.5-turbo", "gpt-3.5-turbo-16k"]
              }
            description: 'A description of the value with type, default value, and description.'
      required:
        - name
        - version
        - protocol_version
        - config_options
```
